version: 2

jobs:
  "python-2.7": &test-template
    docker:
      - image: circleci/python:2.7-stretch-browsers
        environment:
          PYLINTRC: .pylintrc
          TOX: py27
          TOX_PYTHON_27: python

    steps:
      - checkout

      - run:
          name: Write job name
          command: echo $CIRCLE_JOB > circlejob.txt

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "circlejob.txt" }}

      - run:
          name: Install dependencies
          command: |
              sudo pip install virtualenv
              virtualenv venv
              . venv/bin/activate
              pip install tox

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "circlejob.txt" }}
          paths:
              - "venv"
              - ".tox"

      - run:
          name: Run tox
          command: |
              . venv/bin/activate
              tox tox.ini -e $TOX

  "python-3.6":
    <<: *test-template
    docker:
      - image: circleci/python:3.6-stretch-browsers
        environment:
          PYLINTRC: .pylintrc37
          TOX: py36
          TOX_PYTHON_36: python

  "python-3.7":
    <<: *test-template
    docker:
    - image: circleci/python:3.7-stretch-browsers
      environment:
        PYLINTRC37: .pylintrc37
        TOX: py37
        TOX_PYTHON_37: python

  "python-3.8":
    <<: *test-template
    docker:
      - image: circleci/python:3.8-stretch-browsers
        environment:
          PYLINTRC38: .pylintrc37
          TOX: py38
          TOX_PYTHON_38: python

  "python-3.9":
    <<: *test-template
    docker:
      - image: circleci/python:3.9-stretch-browsers
        environment:
          PYLINTRC39: .pylintrc37
          TOX: py39
          TOX_PYTHON_39: python

workflows:
  version: 2
  build:
    jobs:
      - "python-2.7"
      - "python-3.6"
      - "python-3.7"
      - "python-3.8"
      - "python-3.9"
